server:
  port: 8110 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-core # 服务名
  datasource: # mysql数据库连接
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.176.128:3396/srb_core?serverTimezone=GMT%2B8&characterEncoding=utf-8
#    url: jdbc:mysql://192.168.144.129:3396/srb_core?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: 123456
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    host: 192.168.176.128
#    host: 192.168.144.129
    port: 6379
    lettuce:
      pool:
        # redis连接的超时时间  -1不主动中断连接
        max-wait: -1ms
        # 最小的存活的redis连接数 默认0
        min-idle: 8
        # 最大的存活的redis连接数 默认8
        max-idle: 20
        # 服务器运行稳定时 最终保留的redis连接数  默认8
        max-active: 10
#    serialization:
#      write-enums-using-to-string: true
mybatis-plus: #mybatis
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/learn/srb/core/mapper/xml/*.xml
logging:
  level:
    root: info